AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'

Lint/SuppressedException:
  Exclude:
    - 'lib/allowable.rb'

Lint/SendWithMixinArgument:
  Exclude:
    - 'lib/allowable.rb'
    - 'lib/allowable/railtie.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - 'allowable.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'spec/**/*'
    - 'allowable.gemspec'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
