language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.2
  - 2.3.0
  - 2.3.4
  - 2.4.1
  - jruby-9.1.6.0
  - jruby-head
  - rbx-3.74
  - ruby-head

sudo: false

cache: bundler

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.gemfile

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3.74
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
